Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodMissing:
  Enabled: false
